networks:
  backend:

services:
  postgres:
    container_name: tuda-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tuda
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d tuda" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: tuda-minio
    command: server /minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ../volumes/minio:/minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend

  app:
    container_name: tuda-app
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    build:
      context: .
    restart: on-failure
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/tuda
      DB_USERNAME: root
      DB_PASSWORD: root
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: minio123
    ports:
      - "8080:8080"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ../volumes/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - backend
    ports:
      - "9091:9090"

  grafana:
    build: './grafana'
    volumes:
      - ../volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - backend
    ports:
      - "3000:3000"