spring:
  application:
    name: tuda
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    persist-authorization: true


jwt:
  secret: WX5bD8z2FkPqJtRvY7uAeHcLmNpKs4V9wCxE1Z3B6yG0UjIiOoQnMlXaSdRfTg
  lifetime: 30m

s3:
  url: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: tuda

management:
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8090
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include: "*"
    enabled-by-default: false

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true