name: tuda CI/CD

on:
  push:
    branches: [ main ]
    paths: [ '**' ]

env:
  REGISTRY: docker.io
  TUDA_IMAGE_NAME: tuda_app
  GRAFANA_IMAGE_NAME: grafana_custom

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build tuda module with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.TUDA_IMAGE_NAME }}:latest

      - name: Build and push Docker image for Grafana
        uses: docker/build-push-action@v5
        with:
          context: ./grafana
          file: ./grafana/provisioning/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.GRAFANA_IMAGE_NAME }}:latest